version: 0.0
os : linux
files :
  - source : /
    destination: /home/ubuntu/app/step2/zip/
    overwrite : yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location : deploy.sh
      timeout: 60
      runas: ubuntu